name: food_pick
description: "맛집 정보 공유 앱"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.3.4
  image_picker: ^1.0.7
  flutter_naver_map: ^1.2.1
  http: ^1.2.1
  daum_postcode_search: ^0.0.2
  geolocator: ^11.0.0 # 지오코딩(주소 <-> 위경도)
  flutter_inappwebview: ^5.8.0
  intl: ^0.19.0 # DateFormat 을 활용할 수 있는 라이브러리

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
